# Generated by Django 5.2.8 on 2026-01-04 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stats_data', models.JSONField(default=dict)),
                ('last_refreshed', models.DateTimeField(auto_now=True)),
                ('refresh_interval', models.IntegerField(default=300)),
            ],
            options={
                'verbose_name_plural': 'Admin Dashboard Stats',
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('model_type', models.CharField(choices=[('random_forest', 'Random Forest'), ('decision_tree', 'Decision Tree'), ('svm', 'Support Vector Machine'), ('gradient_boosting', 'Gradient Boosting'), ('neural_network', 'Neural Network')], default='random_forest', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('scaler_file', models.FileField(blank=True, null=True, upload_to='scalers/')),
                ('encoder_file', models.FileField(blank=True, null=True, upload_to='encoders/')),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('training_time', models.FloatField(default=0.0)),
                ('test_size', models.FloatField(default=0.2)),
                ('random_state', models.IntegerField(default=42)),
                ('features_used', models.JSONField(blank=True, default=list)),
                ('target_column', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('trained', 'Trained'), ('training', 'Training'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trained_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.JSONField()),
                ('prediction_result', models.JSONField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('model_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('flagged', 'Flagged'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('flag_details', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(default=0.0)),
                ('model_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.mlmodel')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_predictions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('prediction', 'Prediction'), ('model', 'Model'), ('security', 'Security')], default='system', max_length=50)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('related_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.mlmodel')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.predictionlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('system', 'System'), ('database', 'Database'), ('api', 'API'), ('model_training', 'Model Training'), ('prediction', 'Prediction'), ('user', 'User'), ('auth', 'Authentication')], default='system', max_length=50)),
                ('source', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('dataset_file', models.FileField(upload_to='datasets/')),
                ('dataset_type', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('excel', 'Excel')], max_length=10)),
                ('file_size_mb', models.FloatField(default=0.0)),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('column_names', models.JSONField(blank=True, default=list)),
                ('target_column', models.CharField(blank=True, max_length=100)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='training_dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.trainingdataset'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('registration', 'Registration'), ('profile_update', 'Profile Update'), ('prediction', 'Prediction'), ('upload', 'File Upload'), ('password_change', 'Password Change'), ('admin_action', 'Admin Action')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
